import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/componenets/Navbar";
import Footer from "@/componenets/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Here's the magic! We make the body a vertical flex container
        that's at least as tall as the screen.
      */}
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Navbar />

        {/* And here, we tell the main content area to "grow"
          and take up all the available space, pushing the footer down.
        */}
        <main className="flex-grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
